schema_version: 1

context:
  name: opticalglass
  version: "2.0.1"
  python_min: "3.12"
  build_number: 0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 6cade5fcdcf27b0bf640b3065525814b8679cf7668f161fbb6ba0dec9080ad4d

build:
  number: ${{ build_number }}
  noarch: python
  script: ${{ PYTHON }} -m pip install .
  python:
    entry_points:
      - glassmap = opticalglass.glassmapviewer:main

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=83.0.0
    - setuptools-scm
    - pip
  run:
    - python >=${{ python_min }}
    - zemaxglass >=2.0.0
    - numpy >=2.5.1
    - scipy >=1.18.0
    - matplotlib-base >=3.11.1
    - pandas >=3.0.5
    - xlrd >=2.0.2
    - openpyxl >=3.1.5
    - json_tricks >=3.17.3
    - requests >=2.34.2
    - json_tricks >=3.17.3
    - pyyaml >=6.0.3
    - pyside6 >=6.11.1

tests:
  - python:
      imports:
        - opticalglass
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Tools for reading optical material catalogs and libraries
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://pypi.org/project/opticalglass/
  documentation: https://opticalglass.readthedocs.io/
  description: |
   OpticalGlass provides a common API for querying refractive index data and other properties to a number of different optical material data sources. These include:

    * Excel spreadsheets published by optical glass manufacturers
    * Zemax ANSI Glass Format (.agf) files
    * The `RefractiveIndex.INFO <https://refractiveindex.info>`_ database

   The global function `create_glass <https://opticalglass.readthedocs.io/en/latest/opticalglass.html#opticalglass.glassfactory.create_glass>`_ returns a `glass object <https://opticalglass.readthedocs.io/en/stable/opticalglass.html#opticalglass.opticalmedium.OpticalMedium>`_ given a glass name and, optionally, a catalog name. This glass instance can be queried for refractive index and transmittance values.

  repository: https://github.com/mjhoptics/opticalglass

extra:
  recipe-maintainers:
    - mjhoptics
